name: iris-hep-py310
channels:
- conda-forge
dependencies:
- python 3.10.*
- uproot >=5.0.0
- hist >=2.7.0
- mplhep >=0.3.50
- cabinetry >=0.6.0
- coffea >=2024.1.0
- func-adl >=3.3.0
- xrootd >=5.7.0
- dask-awkward >=2024.1.0
- pip
- pip:
  - func-adl-servicex>=2.2
  - servicex>=3.0.0
  - fastjet>=3.4.0.0
