[project]
authors = ["Matthew Feickert <matthew.feickert@cern.ch>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "analysis-systems-env-nightlies"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]

[feature.iris-hep.dependencies]
# Scikit-HEP
uproot = ">=5.0.0"  # versions controlled through coffea
hist = ">=2.7.0"
mplhep = ">=0.3.50"  # hist + plot
cabinetry = ">=0.6.0"
coffea = ">=2024.1.0"
# awkward = "*"  # versions controlled through uproot
# vector = "*"  # versions controlled through fastjet
# iminuit = "*" # versions controlled through cabinetry
# pyhf = "*"  # versions controlled through cabinetry
# IRIS-HEP
func-adl = ">=3.3.0"  # versions controlled through servicex
xrootd = ">=5.7.0"
dask-awkward = ">=2024.1.0"  # versions controlled through coffea

[feature.iris-hep.pypi-dependencies]
func-adl-servicex = ">=2.2"
servicex = ">=3.0.0"  # versions controlled through func-adl-servicex
fastjet = ">=3.4.0.0"

[feature.iris-hep-py38.dependencies]
python = "3.8.*"
# Scikit-HEP
uproot = ">=5.0.0"  # versions controlled through coffea
hist = ">=2.7.0"
mplhep = ">=0.3.50"  # hist + plot
cabinetry = ">=0.6.0"
# coffea = ">=2024.1.0"
# awkward = "*"  # versions controlled through uproot
# vector = "*"  # versions controlled through fastjet
# iminuit = "*" # versions controlled through cabinetry
# pyhf = "*"  # versions controlled through cabinetry
# IRIS-HEP
func-adl = ">=3.3.0"  # versions controlled through servicex
xrootd = ">=5.7.0"
dask-awkward = ">=2024.1.0"  # versions controlled through coffea

[feature.iris-hep-py38.pypi-dependencies]
# coffea on conda-forge seems to be misspecified for Python 3.8
# as only works for coffea = ">=2024.1.0,<2024.3.0"
coffea = ">=2024.1.0"
func-adl-servicex = ">=2.2"
servicex = ">=3.0.0"  # versions controlled through func-adl-servicex
fastjet = ">=3.4.0.0"

[feature.iris-hep-py38.tasks]
export-env = """
mkdir -p iris-hep/3.8 && \
pixi project export conda-environment --environment iris-hep-py38 iris-hep/3.8/environment.yml
"""

export-spec = """
mkdir -p iris-hep/3.8 && \
pixi project export conda-explicit-spec --environment iris-hep-py38 --locked --ignore-pypi-errors iris-hep/3.8/
"""

[feature.py39.dependencies]
python = "3.9.*"

[feature.py39.tasks]
export-env = """
mkdir -p iris-hep/3.9 && \
pixi project export conda-environment --environment iris-hep-py39 iris-hep/3.9/environment.yml
"""

export-spec = """
mkdir -p iris-hep/3.9 && \
pixi project export conda-explicit-spec --environment iris-hep-py39 --locked --ignore-pypi-errors iris-hep/3.9/
"""

[feature.py310.dependencies]
python = "3.10.*"

[feature.py310.tasks]
export-env = """
mkdir -p iris-hep/3.10 && \
pixi project export conda-environment --environment iris-hep-py310 iris-hep/3.10/environment.yml
"""

export-spec = """
mkdir -p iris-hep/3.10 && \
pixi project export conda-explicit-spec --environment iris-hep-py310 --locked --ignore-pypi-errors iris-hep/3.10/
"""

[feature.py311.dependencies]
python = "3.11.*"

[feature.py311.tasks]
export-env = """
mkdir -p iris-hep/3.11 && \
pixi project export conda-environment --environment iris-hep-py311 iris-hep/3.11/environment.yml
"""

export-spec = """
mkdir -p iris-hep/3.11 && \
pixi project export conda-explicit-spec --environment iris-hep-py311 --locked --ignore-pypi-errors iris-hep/3.11/
"""

[feature.py312.dependencies]
python = "3.12.*"

[feature.py312.tasks]
export-env = """
mkdir -p iris-hep/3.12 && \
pixi project export conda-environment --environment iris-hep-py312 iris-hep/3.12/environment.yml
"""

export-spec = """
mkdir -p iris-hep/3.12 && \
pixi project export conda-explicit-spec --environment iris-hep-py312 --locked --ignore-pypi-errors iris-hep/3.12/
"""

[environments]

iris-hep = ["iris-hep"]

iris-hep-py38 = ["iris-hep-py38"]

iris-hep-py39 = ["py39", "iris-hep"]

iris-hep-py310 = ["py310", "iris-hep"]

iris-hep-py311 = ["py311", "iris-hep"]

iris-hep-py312 = ["py312", "iris-hep"]
