[project]
authors = ["Matthew Feickert <matthew.feickert@cern.ch>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "analysis-systems-env-nightlies"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]

[feature.iris-hep.dependencies]
# Scikit-HEP
uproot = ">=5.0.0"  # versions controlled through coffea
hist = ">=2.7.0"
mplhep = ">=0.3.50"  # hist + plot
cabinetry = ">=0.6.0"
coffea = ">=2024.1.0"
# awkward = "*"  # versions controlled through uproot
# vector = "*"  # versions controlled through fastjet
# iminuit = "*" # versions controlled through cabinetry
# pyhf = "*"  # versions controlled through cabinetry
# IRIS-HEP
func-adl = "*"  # versions controlled through servicex
xrootd = ">=5.7.0"
dask-awkward = ">=2024.1.0"  # versions controlled through coffea

[feature.iris-hep.pypi-dependencies]
func-adl-servicex = ">=2.2"
servicex = ">=3.0.0"  # versions controlled through func-adl-servicex

[feature.py39.dependencies]
python = "3.9.*"

[feature.py311.dependencies]
python = "3.11.*"

[feature.py312.dependencies]
python = "3.12.*"

[environments]

iris-hep = ["iris-hep"]

iris-hep-39 = ["py39", "iris-hep"]

iris-hep-311 = ["py311", "iris-hep"]

iris-hep-312 = ["py312", "iris-hep"]
