name: iris-hep-rc

channels:
  - conda-forge

dependencies:
  - python=3.11
  # Scikit-HEP
  - uproot>=5.0.0  # versions controlled through coffea
  - hist>=2.7.0
  - mplhep>=0.3.50  # hist + plot
  - cabinetry>=0.6.2
  - awkward  # versions controlled through uproot
  - vector  # versions controlled through fastjet
  - iminuit  # versions controlled through cabinetry
  - pyhf  # versions controlled through cabinetry
  - coffea>=2024.1.0
  # IRIS-HEP
  - dask-awkward>=2024.1.0 # versions controlled through coffea, last with awkward v1
  - xrootd>=5.7.0
  - func-adl  # versions controlled through servicex
  # pip dependencies
  - pip
  - pip:
    - fastjet>=3.4.0.0
    - servicex>=3.0.0
    - func-adl-servicex>=2.2

# conda-lock only
platforms:
  - linux-64
