name: Test environments

on:
  push:
  # Run daily at 0:01 UTC
  schedule:
  - cron:  '1 0 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scikit-hep:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.11']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Ask for environment
      run: env

    - name: Check job
      run: echo ${{ jobs.scikit-hep.name }}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --upgrade pip-tools

    - name: Build lock file
      run: |
        pip-compile \
          --resolver=backtracking \
          --generate-hashes \
          --output-file ${{ matrix.python-version}}-"${GITHUB_JOB}"-requirements.lock \
          "${GITHUB_JOB}"/requirements.txt

    - name: Install from lock file
      run: |
        python -m pip install \
          --upgrade \
          --require-hashes \
          --requirement ${{ matrix.python-version}}-"${GITHUB_JOB}"-requirements.lock

    - name: List Python dependencies
      run: |
        python -m pip list

    - name: Upload lock file
      uses: actions/upload-artifact@v3
      with:
        name: "${GITHUB_JOB}"
        path: ${{ matrix.python-version}}-"${GITHUB_JOB}"-requirements.lock
